**We want to make sure that whatever data we are giving to embedding layer that should be integer encoded, and the embedding layer automatically handles the data**

In [ ]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'Jai Shree Ram']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [4, 4, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 5, 3],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 5, 3],
 [3, 16, 17]]

In [ ]:
#Whatever input we are giving should be of equal shape and that is why we are using padding
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 4,  4, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  5,  3,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  5,  3,  0],
       [ 3, 16, 17,  0,  0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=17, output_dim=2, input_length=5))
model.build(input_shape=(None, 5))  # Build the model with the expected input shape

model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 5, 2)           │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
import numpy as np

sequences = np.array([
    [1, 2, 3, 4, 5],
    [0, 1, 2, 3, 4],
    [16, 15, 14, 13, 12],
    [3, 3, 3, 3, 3],
    [10, 11, 12, 13, 14],
    [6, 7, 8, 9, 10],
    [0, 0, 0, 0, 0],
    [5, 4, 3, 2, 1],
    [7, 6, 5, 4, 3],
    [2, 1, 0, 16, 15]  # Make sure max is 16, not more
])

print(np.max(sequences))  # This should be <= 16

16


In [ ]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[[ 0.02878674 -0.04959372]
  [ 0.04992208 -0.03265202]
  [-0.00040146  0.0437286 ]
  [-0.02535806 -0.03089802]
  [ 0.04935724 -0.0209258 ]]

 [[-0.04639468 -0.02530605]
  [ 0.02878674 -0.04959372]
  [ 0.04992208 -0.03265202]
  [-0.00040146  0.0437286 ]
  [-0.02535806 -0.03089802]]

 [[ 0.00650603  0.01401336]
  [-0.0433663  -0.04064214]
  [-0.04077367  0.04325921]
  [ 0.04511687  0.00845381]
  [-0.01832796 -0.00859209]]

 [[-0.00040146  0.0437286 ]
  [-0.00040146  0.0437286 ]
  [-0.00040146  0.0437286 ]
  [-0.00040146  0.0437286 ]
  [-0.00040146  0.0437286 ]]

 [[-0.01818573  0.01779559]
  [-0.02198769  0.02297847]
  [-0.01832796 -0.00859209]
  [ 0.04511687  0.00845381]
  [-0.04077367  0.04325921]]

 [[ 0.01298455  0.02082603]
  [ 0.04712098  0.01548395]
  [ 0.00809914  0.04864864]
  [-0.04984507 -0.03822771]
  [-0.01818573  0.01779559]]

 [[-0.04639468 -0.02530605]
  [-0.04639468 -0.02530605]
  [-0.04639468 -0.02530605]
  [-0.04639468 -0.02530605

**Running the embedding layer on keras inbuilt dataset of imdb**

In [ ]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

import numpy as np

dummy_input = np.random.randint(0, 10000, size=(1, 50))  # shape = (1, 50)
model.predict(dummy_input)

model.summary()  # Now shows actual parameters


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 538ms/step


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (1, 50, 2)             │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (1, 32)                │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (1, 1)                 │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)